// Generated by CoffeeScript 1.6.3
(function() {
  var Beer, default_verse, verse_one, verse_two, verse_zero;

  Beer = function() {};

  module.exports = Beer;

  Beer.verse = function(num) {
    if ((num === 2)({
      verse_two: verse_two
    })) {

    } else if ((num === 1)({
      verse_one: verse_one
    })) {

    } else if ((num === 0)({
      verse_zero: verse_zero
    })) {

    } else {
      return {
        default_verse: num
      };
    }
  };

  Beer.sing = function(start, stop) {
    var i, message;
    stop = stop || 0;
    message = "";
    i = start;
    while (i >= stop) {
      message += {
        verse: i
      };
      if (i > stop) {
        message += "\n";
      }
      i--;
    }
    return message;
  };

  default_verse = function(num) {
    var message;
    message = num + " bottles of beer on the wall, ";
    message += num + " bottles of beer.\n";
    message += "Take one down and pass it around, ";
    message += (num - 1) + " bottles of beer on the wall.\n";
    return message;
  };

  verse_two = function() {
    var message;
    message = "2 bottles of beer on the wall, ";
    message += "2 bottles of beer.\n";
    message += "Take one down and pass it around, ";
    message += "1 bottle of beer on the wall.\n";
    return message;
  };

  verse_one = function() {
    var message;
    message = "1 bottle of beer on the wall, ";
    message += "1 bottle of beer.\n";
    message += "Take it down and pass it around, ";
    message += "no more bottles of beer on the wall.\n";
    return message;
  };

  verse_zero = function() {
    var message;
    message = "No more bottles of beer on the wall, ";
    message += "no more bottles of beer.\n";
    message += "Go to the store and buy some more, ";
    message += "99 bottles of beer on the wall.\n";
    return message;
  };

}).call(this);
